[[redirects]]
  from = "/exemples/labaiedudragon"
  to = "https://baiedudragon.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/exemples/labaiedudragon/*"
  to = "https://baiedudragon.netlify.app/:splat"
  status = 200
  force = true
